version: "3.7"

services:

  flask:
    build: ./flask
    image: flask:latest
    container_name: flask
    restart: always
    environment:
      - APP_NAME=AgroBackend
    expose:
      - 8080

  nginx: 
    build: ./nginx
    image: nginx:flask
    container_name: nginx
    restart: always
    ports:
      - "80:80"